### ISSUE TITLE
PA Review: New Account Creation, Login, and Demo Login

### ISSUE THREAD

**Issue by andrewopes789** [andrewopes789/carstagram#1]
- [x] Backend: DB, model, controller, view
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by dallashall** [comment]
Just a few things before I approve this:
- [ ] Add css style of cursor:pointer for your login, demo, and signup buttons
- [ ] Fix bug with signing up (currently does not work on live-site)

**Comment by dallashall** [comment]
Looks good!
