### ISSUE TITLE
PA Review: Likes

### ISSUE THREAD

**Issue by andrewopes789** [andrewopes789/carstagram#4]
- [x] Backend: DB, model, controller, view
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by dallashall** [comment]
Ideally, when I click on the heart in the navbar, I would like to see all of my favorited photos.
